import { test, expect, axeScan } from '../support/fixtures'
import type { Page } from '@playwright/test'

test.beforeEach(async ({ page }) => {
	await page.goto('/checkbox-contracts')
})

const subject = (page: Page) => page.locator('#subject')
const events = async (page: Page) => JSON.parse(await page.getByTestId('events').textContent()) as string[]
const box = (page: Page, name: string) => page.locator('.bunt-checkbox').filter({ has: page.getByRole('checkbox', { name }) }).locator('.bunt-checkbox-box')

test('routes root and control attributes, live naming and merged descriptions without duplicates', async ({ page, pageLog }) => {
	const control = subject(page)
	const root = page.locator('.bunt-checkbox.original')
	await expect(root).toHaveAttribute('data-case', 'initial')
	await expect(root).toHaveAttribute('lang', 'en')
	await expect(root).toHaveAttribute('dir', 'ltr')
	await expect(root).toHaveAttribute('title', 'Title')
	await expect(control).not.toHaveAttribute('title')
	await expect(root).not.toHaveAttribute('id')
	await expect(root).not.toHaveAttribute('name')
	await expect(control).toHaveAttribute('name', 'consent')
	await expect(control).toHaveAttribute('form', 'checkbox-form')
	await expect(control).not.toHaveAttribute('class')
	await expect(control).not.toHaveAttribute('data-case')
	await expect(control).not.toHaveAttribute('lang')
	await expect(control).toHaveAccessibleName('Slot label')
	await expect(control).toHaveAttribute('aria-describedby', 'extra')
	await expect(control).toHaveAccessibleDescription('Caller description')
	await page.getByRole('button', { name: 'Change bindings' }).click()
	const changed = page.locator('#changed-subject')
	await expect(subject(page)).toHaveCount(0)
	await expect(page.locator('[id="changed-subject"]')).toHaveCount(1)
	await expect(page.locator('.bunt-checkbox.alternate')).toHaveAttribute('dir', 'rtl')
	await expect(page.locator('.bunt-checkbox.alternate')).toHaveAttribute('data-case', 'changed')
	await expect(changed).toHaveAttribute('name', 'changed')
	await expect(changed).toHaveAttribute('form', 'other-form')
	await expect(changed).toHaveAttribute('aria-describedby', 'extra second')
	await expect(changed).toHaveAttribute('aria-labelledby', `changed-subject-label`)
	await expect(changed).toHaveAccessibleName('Slot label')
	await page.getByRole('button', { name: 'Change name', exact: true }).click()
	await expect(changed).toHaveAccessibleName('Caller name')
	await page.getByRole('button', { name: 'Change name', exact: true }).click()
	await expect(changed).toHaveAccessibleName('Second description')
	const ids = await page.locator('[id]').evaluateAll(elements => elements.map(element => element.id))
	expect(new Set(ids).size).toBe(ids.length)
	expect(pageLog.vueWarnings).toEqual([])
})

test('enabled activation forwards original native events once and updates the boolean model', async ({ page }) => {
	await box(page, 'Slot label').click()
	await expect(page.getByTestId('checked')).toHaveText('true')
	await expect(subject(page)).toBeChecked()
	expect((await events(page)).filter(value => value !== 'focus')).toEqual(['click:true:true', 'input:true:true', 'change:true:true', 'model:true'])
	await page.getByRole('button', { name: 'Clear events' }).click()
	await page.getByText('Slot label').click()
	await expect(page.getByTestId('checked')).toHaveText('false')
	await subject(page).press('Space')
	await expect(page.getByTestId('checked')).toHaveText('true')
	await subject(page).press('a')
	const recorded = await events(page)
	expect(recorded.filter(value => value.startsWith('input:'))).toEqual(['input:true:true', 'input:true:true'])
	expect(recorded.filter(value => value.startsWith('change:'))).toEqual(['change:true:true', 'change:true:true'])
	expect(recorded).toContain('key-a:true:true')
	await page.getByText('External name').click()
	await expect(page.getByTestId('checked')).toHaveText('false')
})

for (const initial of ['unchecked', 'checked']) {
	test(`disabled ${initial} checkbox stays focusable and blocks every activation and implicit submission`, async ({ page }) => {
		if (initial === 'checked') await page.getByRole('button', { name: 'Update models' }).click()
		const expected = initial === 'checked' ? 'true' : 'false'
		await subject(page).focus()
		await page.getByRole('button', { name: 'Toggle disabled' }).click()
		const control = subject(page)
		await expect(control).toBeFocused()
		await expect(control).toHaveAttribute('aria-disabled', 'true')
		await expect(control).not.toHaveAttribute('disabled')
		await page.getByRole('button', { name: 'Clear events' }).click()
		await box(page, 'Slot label').click({ force: true })
		await page.getByText('Slot label').click({ force: true })
		await page.getByText('External name').click({ force: true })
		await control.click({ force: true })
		await control.focus()
		await control.press('Space')
		await control.press('Enter')
		await control.evaluate(el => (el as HTMLInputElement).click())
		await expect(page.getByTestId('checked')).toHaveText(expected)
		await expect(control).toBeChecked({ checked: initial === 'checked' })
		expect((await events(page)).filter(value => /^(input|change):/.test(value))).toEqual([])
		await expect(page.getByTestId('submits')).toHaveText('0')
		await page.getByRole('button', { name: 'Update models' }).click()
		await expect(control).toBeChecked({ checked: initial !== 'checked' })
		await page.getByRole('button', { name: 'Toggle disabled' }).click()
		await control.focus()
		await control.press('Space')
		await expect(control).toBeChecked({ checked: initial === 'checked' })
		await page.getByRole('textbox', { name: 'Enabled submit' }).fill('ready')
		await page.getByRole('textbox', { name: 'Enabled submit' }).press('Enter')
		await expect(page.getByTestId('submits')).toHaveText('1')
	})
}

test('a disabled toggle that bypasses the click guard is reverted without forwarding events', async ({ page }) => {
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await page.evaluate(() => document.addEventListener('click', event => {
		if ((event.target as Element).id === 'subject') event.stopPropagation()
	}, { capture: true }))
	await page.getByRole('button', { name: 'Clear events' }).click()
	await subject(page).evaluate(el => (el as HTMLInputElement).click())
	await expect(subject(page)).not.toBeChecked()
	await expect(page.getByTestId('checked')).toHaveText('false')
	expect(await events(page)).toEqual([])
})

test('empty label content leaves naming to an external label, and a caller aria-checked is dropped', async ({ page }) => {
	const control = page.locator('#empty-slot')
	await expect(control).toHaveAccessibleName('External only')
	await expect(control).not.toHaveAttribute('aria-labelledby')
	await page.getByRole('button', { name: 'Toggle empty slot content' }).click()
	await expect(control).toHaveAccessibleName('Slot now names it')
	await expect(page.getByRole('checkbox', { name: 'Readonly attribute' })).not.toHaveAttribute('aria-checked')
})

test('an initially disabled checked checkbox keeps its value and respects caller tabindex', async ({ page }) => {
	const control = page.getByRole('checkbox', { name: 'Checked disabled' })
	await expect(control).toHaveAttribute('tabindex', '-1')
	await control.focus()
	await expect(control).toBeFocused()
	await control.press('Space')
	await page.getByText('Checked disabled').click({ force: true })
	await expect(page.getByTestId('second')).toHaveText('true')
	await expect(control).toBeChecked()
	await page.getByRole('checkbox', { name: 'Slot label' }).focus()
	await page.keyboard.press('Tab')
	await expect(page.getByRole('textbox', { name: 'Enabled submit' })).toBeFocused()
})

test('public focus and whole-component boundaries emit once, hidden and inert depart, unmount stays silent', async ({ page }) => {
	await page.getByRole('button', { name: 'Focus checkbox' }).click()
	await expect(subject(page)).toBeFocused()
	await subject(page).evaluate(el => (el as HTMLInputElement).blur())
	await expect(page.getByTestId('events')).toHaveText('["focus","blur"]')
	await page.getByRole('button', { name: 'Focus checkbox' }).click()
	await page.getByRole('button', { name: 'Toggle hidden' }).click()
	await expect(page.getByTestId('events')).toHaveText('["focus","blur","focus","blur"]')
	await page.getByRole('button', { name: 'Focus checkbox' }).click()
	await expect(page.getByRole('button', { name: 'Focus checkbox' })).toBeFocused()
	await page.getByRole('button', { name: 'Toggle hidden' }).click()
	await page.getByRole('button', { name: 'Focus checkbox' }).click()
	await page.getByRole('button', { name: 'Toggle inert' }).click()
	await expect(page.getByTestId('events')).toHaveText('["focus","blur","focus","blur","focus","blur"]')
	await page.getByRole('button', { name: 'Toggle inert' }).click()
	await page.getByRole('button', { name: 'Clear events' }).click()
	await page.getByRole('button', { name: 'Focus checkbox' }).click()
	await page.getByRole('button', { name: 'Toggle mounted' }).click()
	await expect(page.getByTestId('events')).toHaveText('["focus"]')
})

test('keyboard focus is visible on the box, enabled and disabled', async ({ page }) => {
	await page.getByRole('button', { name: 'Clear events' }).focus()
	await page.keyboard.press('Tab')
	await expect(subject(page)).toBeFocused()
	// the box has `transition: all`, so poll past the outline transition
	const ring = () => box(page, 'Slot label').evaluate(node => [getComputedStyle(node).outlineStyle, getComputedStyle(node).outlineWidth])
	await expect.poll(ring).toEqual(['solid', '2px'])
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(subject(page)).toBeFocused()
	await expect.poll(ring).toEqual(['solid', '2px'])
	await page.getByRole('button', { name: 'Outside', exact: true }).focus()
	await expect.poll(async () => (await ring())[0]).toBe('none')
})

test('label slot wins over the prop, which wins over the default slot, with live changes', async ({ page }) => {
	const control = page.getByRole('checkbox').first()
	await expect(control).toHaveAccessibleName('Slot label')
	await page.getByRole('button', { name: 'Toggle label slot' }).click()
	await expect(control).toHaveAccessibleName('Prop label')
	await page.getByRole('button', { name: 'Toggle label text' }).click()
	await expect(control).toHaveAccessibleName('Default label')
	await page.getByText('Default label').click()
	await expect(page.getByTestId('checked')).toHaveText('true')
	await page.getByRole('button', { name: 'Toggle label slot' }).click()
	await expect(control).toHaveAccessibleName('Slot label')
	await expect(page.getByText('Default label')).toHaveCount(0)
	await page.getByRole('button', { name: 'Toggle label text' }).click()
	await page.getByRole('button', { name: 'Toggle label slot' }).click()
	await expect(control).toHaveAccessibleName('Prop label')
	await page.getByText('Prop label').click()
	await expect(page.getByTestId('checked')).toHaveText('false')
})

test('disabled explanation reaches the checkbox through caller descriptions without tooltip integration', async ({ page, pageLog }) => {
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	const control = subject(page)
	await control.focus()
	await control.hover({ force: true })
	await expect(control).toHaveAccessibleDescription('Caller description')
	await expect(page.locator('.bunt-tooltip')).toHaveCount(0)
	const marked = await page.locator('.bunt-checkbox, .bunt-checkbox *').evaluateAll(nodes => nodes.flatMap(node => [...node.attributes].map(attribute => attribute.name)).filter(name => name.startsWith('data-bunt') || name === 'tooltip'))
	expect(marked).toEqual([])
	await page.getByRole('button', { name: 'Change bindings' }).click()
	await expect(page.locator('#changed-subject')).toHaveAccessibleDescription('Caller description Second description')
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(page.locator('#changed-subject')).toHaveAccessibleDescription('Caller description Second description')
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(page.locator('#changed-subject')).toHaveAccessibleDescription('Caller description Second description')
	expect(pageLog.vueWarnings).toEqual([])
})

test('checked, unchecked, enabled and disabled states pass axe and expose their state', async ({ page }) => {
	await expect((await axeScan(page, 'main')).violations).toEqual([])
	await expect(page.locator('form')).toMatchAriaSnapshot(`
		- checkbox "Slot label"
		- checkbox "Checked disabled" [checked] [disabled]
	`)
	await page.getByRole('button', { name: 'Update models' }).click()
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(page.locator('form')).toMatchAriaSnapshot(`
		- checkbox "Slot label" [checked] [disabled]
		- checkbox "Checked disabled" [disabled]
	`)
	await expect((await axeScan(page, 'main')).violations).toEqual([])
})

test('a readonly attribute is routed natively and does not simulate readonly', async ({ page, pageLog }) => {
	const control = page.getByRole('checkbox', { name: 'Readonly attribute' })
	await expect(control).toHaveAttribute('readonly', '')
	await expect(control.locator('xpath=ancestor::*[contains(@class, "bunt-checkbox")][1]')).not.toHaveAttribute('readonly')
	await page.getByText('Readonly attribute').click()
	await expect(page.getByTestId('third')).toHaveText('true')
	expect(pageLog.vueWarnings).toEqual([])
})

test('source API consumer binds the boolean model, native events, both label slots and ref focus', async ({ page, pageLog }) => {
	await page.goto('/field-api-cases')
	const agree = page.getByRole('checkbox', { name: 'Agree' })
	await agree.check()
	await expect(page.getByTestId('agreed')).toHaveText('true')
	await expect(page.getByRole('checkbox', { name: 'Default slot' })).toBeChecked()
	await page.getByRole('button', { name: 'Focus checkbox' }).click()
	await expect(agree).toBeFocused()
	expect(pageLog.vueWarnings).toEqual([])
})

test('source SSR hydrates unique stable checkbox IDs and associations', async ({ page, request, pageLog }) => {
	const response = await request.get('/ssr-checkboxes?ssr')
	expect(response.ok()).toBeTruthy()
	const html = await response.text()
	const serverIds = [...html.matchAll(/<input[^>]*\bid="([^"]+)"/g)].map(match => match[1])
	expect(serverIds).toHaveLength(3)
	expect(new Set(serverIds).size).toBe(3)
	await page.goto('/ssr-checkboxes?ssr')
	expect(await page.locator('input').evaluateAll(nodes => nodes.map(node => node.id))).toEqual(serverIds)
	expect(pageLog.matching(/hydration|mismatch/i)).toEqual([])
	await expect(page.getByRole('checkbox', { name: 'First' })).toBeChecked()
	await expect(page.getByRole('checkbox', { name: 'First' })).toHaveAccessibleDescription('Checkbox note')
	await expect(page.getByRole('checkbox', { name: 'Second' })).toBeVisible()
	await expect(page.getByRole('checkbox', { name: 'Third' })).toHaveAttribute('aria-disabled', 'true')
	await page.getByRole('checkbox', { name: 'Second' }).check()
	await expect(page.getByRole('checkbox', { name: 'Second' })).toBeChecked()
})

test.describe('forced colours', () => {
	test.use({ forcedColors: 'active' })

	test('disabled state stays distinguishable and focus remains visible', async ({ page }) => {
		expect(await page.evaluate(() => matchMedia('(forced-colors: active)').matches)).toBe(true) // setup evidence only
		const colour = (name: string) => page.locator('.bunt-checkbox').filter({ has: page.getByRole('checkbox', { name }) }).locator('label').evaluate(node => getComputedStyle(node).color)
		expect(await colour('Checked disabled')).not.toBe(await colour('Slot label'))
		const enabledBox = box(page, 'Slot label')
		expect(await enabledBox.evaluate(el => getComputedStyle(el).getPropertyValue('forced-color-adjust'))).not.toBe('none')
		await page.getByRole('button', { name: 'Clear events' }).focus()
		await page.keyboard.press('Tab')
		expect(await enabledBox.evaluate(node => getComputedStyle(node).outlineStyle)).toBe('solid')
		const glyph = (name: string) => box(page, name).locator('.mdi')
		await expect(glyph('Slot label')).toHaveCSS('opacity', '0')
		await page.getByRole('button', { name: 'Update models' }).click()
		await expect(glyph('Slot label')).toHaveCSS('opacity', '1')
		const [glyphColour, boxBackground] = await glyph('Slot label').evaluate(node => [getComputedStyle(node).color, getComputedStyle(node.parentElement).backgroundColor])
		expect(glyphColour).not.toBe(boxBackground)
	})
})
