import { test, expect, axeScan } from '../support/fixtures'

test.beforeEach(async ({ page }) => {
	await page.goto('/field-contracts')
})

test('routes changing native attributes, naming and merged hint descriptions', async ({ page, pageLog }) => {
	const input = page.locator('#external')
	await expect(input).toHaveAccessibleName('Input label')
	await expect(input).toHaveAttribute('name', 'entry')
	await expect(input).toHaveAttribute('maxlength', '20')
	await expect(input).toHaveAttribute('aria-describedby', 'extra external-hint')
	await expect(input).toHaveAccessibleDescription('Caller description Input guidance')
	await expect(page.locator('.original').first()).toHaveAttribute('lang', 'en')
	await page.getByRole('button', { name: 'Change bindings' }).click()
	const changed = page.locator('#changed-input')
	await expect(changed).toHaveAttribute('maxlength', '8')
	await expect(changed).toHaveAttribute('aria-describedby', 'extra second changed-input-hint')
	await expect(page.locator('#external')).toHaveCount(0)
	await expect(page.locator('.alternate').first()).toHaveAttribute('dir', 'rtl')
	await expect(page.locator('[id="changed-input"]')).toHaveCount(1)
	await page.getByRole('button', { name: 'Toggle validation' }).click()
	await expect(changed).toHaveAccessibleDescription('Caller description Second description Validation message')
	await expect(changed).toHaveAttribute('aria-invalid', 'true')
	await expect(pageLog.vueWarnings).toEqual([])
})

test('forwards original native events once and option commits emit no native input/change', async ({ page }) => {
	await page.locator('#external').fill('Typed')
	await expect(page.getByTestId('text')).toHaveText('Typed')
	await expect(page.getByTestId('events')).toContainText('input:true:true')
	await page.locator('#external').press('Enter')
	await expect(page.getByTestId('events')).toContainText('enter:true:true')
	await page.getByRole('button', { name: 'Clear events' }).click()
	const select = page.getByRole('combobox', { name: 'Select label' })
	await select.fill('Bet')
	await expect(page.getByTestId('events')).toContainText('search:true:true')
	await expect(page.getByTestId('selected')).toHaveText('a')
	await page.getByRole('option', { name: 'Beta' }).click()
	await expect(page.getByTestId('selected')).toHaveText('b')
	const events = JSON.parse(await page.getByTestId('events').textContent())
	expect(events.filter(value => value.startsWith('search:'))).toHaveLength(1)
	expect(events.filter(value => value.startsWith('select-change:'))).toHaveLength(0)
})

test('public focus avoids opening and focus events track popup and external boundaries', async ({ page }) => {
	await page.getByRole('button', { name: 'Focus select', exact: true }).click()
	const select = page.getByRole('combobox', { name: 'Select label' })
	await expect(select).toBeFocused()
	await expect(select).toHaveAttribute('aria-expanded', 'false')
	await select.press('ArrowDown')
	await expect(select).toHaveAttribute('aria-expanded', 'true')
	await page.getByRole('button', { name: 'Popup help' }).focus()
	await expect(page.getByTestId('events')).toHaveText('["select-focus"]')
	await page.getByRole('button', { name: 'Outside', exact: true }).focus()
	await expect(page.getByTestId('events')).toHaveText('["select-focus","select-blur"]')
	await expect(select).toHaveAttribute('aria-expanded', 'false')
	await select.focus()
	await select.evaluate(el => (el as HTMLInputElement).blur())
	await expect(page.getByTestId('events')).toHaveText('["select-focus","select-blur","select-focus","select-blur"]')
})

test('disabled keeps focus, preserves drafts, blocks activation and obeys application updates', async ({ page }) => {
	const select = page.getByRole('combobox', { name: 'Select label' })
	await select.fill('draft')
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(select).toBeFocused()
	await expect(select).toHaveAttribute('aria-expanded', 'false')
	await expect(select).toHaveAttribute('aria-disabled', 'true')
	await expect(select).toHaveValue('draft')
	await select.press('ArrowDown')
	await select.press('Enter')
	await select.press('x')
	await expect(select).toHaveValue('draft')
	await expect(page.getByTestId('submits')).toHaveText('0')
	await expect(page.getByTestId('selected')).toHaveText('a')
	await page.getByRole('button', { name: 'Update models' }).click()
	await expect(select).toHaveValue('Beta')
	await expect(page.locator('#external')).toHaveValue('Application')
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(select).toHaveAttribute('aria-expanded', 'false')
	await select.press('ArrowDown')
	await page.getByRole('button', { name: 'Popup help' }).focus()
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(select).toBeFocused()
	await page.getByRole('textbox', { name: 'Enabled submit' }).fill('ready')
	await page.getByRole('textbox', { name: 'Enabled submit' }).press('Enter')
	await expect(page.getByTestId('submits')).toHaveText('1')
})

test('readonly select allows inspection and navigation without committing', async ({ page }) => {
	await page.getByRole('button', { name: 'Toggle readonly' }).click()
	const select = page.getByRole('combobox', { name: 'Select label' })
	await select.click()
	await select.press('ArrowDown')
	await select.press('Enter')
	await expect(page.getByTestId('selected')).toHaveText('a')
	await page.getByRole('option', { name: 'Beta' }).click()
	await expect(page.getByTestId('selected')).toHaveText('a')
	await expect(select).toHaveAttribute('aria-expanded', 'true')
	await select.press('Escape')
	await expect(select).toHaveAttribute('aria-expanded', 'false')
})

test('hidden/inert departure emits once while unmount remains silent', async ({ page }) => {
	await page.getByRole('button', { name: 'Focus input', exact: true }).click()
	await page.getByRole('button', { name: 'Toggle hidden' }).click()
	await expect(page.getByTestId('events')).toHaveText('["input-focus","input-blur"]')
	await page.getByRole('button', { name: 'Toggle hidden' }).click()
	await page.getByRole('button', { name: 'Focus input', exact: true }).click()
	await page.getByRole('button', { name: 'Toggle inert' }).click()
	await expect(page.getByTestId('events')).toHaveText('["input-focus","input-blur","input-focus","input-blur"]')
	await page.getByRole('button', { name: 'Toggle inert' }).click()
	await page.getByRole('button', { name: 'Focus input', exact: true }).click()
	await page.getByRole('button', { name: 'Toggle mounted' }).click()
	await expect(page.getByTestId('events')).toHaveText('["input-focus","input-blur","input-focus","input-blur","input-focus"]')
})

for (const name of ['Input', 'Select']) {
	test(`${name} disabled guidance stays associated through binding changes`, async ({ page, pageLog }) => {
		await page.getByRole('button', { name: 'Toggle disabled' }).click()
		const control = page.locator(name === 'Input' ? '#external' : '#select-entry')
		await control.focus()
		await expect(control).toHaveAccessibleDescription(`Caller description ${name} guidance`)
		await page.getByRole('button', { name: 'Change bindings' }).click()
		const changed = page.locator(name === 'Input' ? '#changed-input' : '#changed-select')
		await expect(changed).toHaveAccessibleDescription(`Caller description Second description ${name} guidance`)
		expect(pageLog.vueWarnings).toEqual([])
	})
}

test('accessible field states pass axe and compact guidance remains hidden', async ({ page }) => {
	await expect((await axeScan(page, 'main')).violations).toEqual([])
	await page.getByRole('button', { name: 'Toggle compact' }).click()
	await expect(page.getByText('Input guidance')).toBeHidden()
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect((await axeScan(page, 'form')).violations).toEqual([])
})

for (const type of ['text', 'search', 'email', 'url', 'tel', 'password', 'number']) {
	test(`${type} input uses a focusable native editing lock`, async ({ page }) => {
		await page.getByRole('combobox', { name: 'Type', exact: true }).selectOption(type)
		const input = page.locator('#external')
		await input.fill(type === 'number' ? '42' : 'Value')
		await page.getByRole('button', { name: 'Toggle disabled' }).click()
		await expect(input).toBeFocused()
		await expect(input).toHaveAttribute('readonly', '')
		await input.press('ArrowUp')
		await input.press('x')
		await expect(input).toHaveValue(type === 'number' ? '42' : 'Value')
		await input.press('Tab')
		await expect(page.locator('#select-entry')).toBeFocused()
	})
}

test('source SSR hydrates unique stable IDs and associations in one application', async ({ page, request, pageLog }) => {
	const response = await request.get('/ssr-fields?ssr')
	expect(response.ok()).toBeTruthy()
	const html = await response.text()
	expect(html).not.toContain('NaN')
	const serverIds = [...html.matchAll(/<input[^>]*\bid="([^"]+)"/g)].map(match => match[1])
	expect(serverIds).toHaveLength(4)
	expect(new Set(serverIds).size).toBe(4)
	await page.goto('/ssr-fields?ssr')
	await expect(page.getByRole('textbox', { name: 'First' })).toHaveValue('One')
	const clientIds = await page.locator('input').evaluateAll(entries => entries.map(entry => entry.id))
	expect(clientIds).toEqual(serverIds)
	expect(pageLog.matching(/hydration|mismatch/i)).toEqual([])
	await expect(page.getByRole('textbox', { name: 'First' })).toHaveAccessibleDescription('First hint')
})

test('caller naming precedence, external labels and tabindex remain native', async ({ page }) => {
	const entry = page.locator('#external')
	await page.getByText('External name', { exact: true }).click()
	await expect(entry).toBeFocused()
	await page.getByRole('button', { name: 'Change name', exact: true }).click()
	await expect(entry).toHaveAccessibleName('Caller name')
	await page.getByRole('button', { name: 'Change name', exact: true }).click()
	await expect(entry).toHaveAccessibleName('Second description')
	await expect(page.getByRole('textbox', { name: 'Disabled required' })).toHaveAttribute('tabindex', '-1')
	await page.getByRole('textbox', { name: 'Disabled required' }).focus()
	await expect(page.getByRole('textbox', { name: 'Disabled required' })).toBeFocused()
})

for (const state of ['disabled', 'readonly']) {
	test(`${state} blocks paste/drop/beforeinput and ignores late composition input`, async ({ page }) => {
		await page.getByRole('button', { name: `Toggle ${state}`, exact: true }).click()
		for (const id of ['external', 'select-entry']) {
			const entry = page.locator(`#${id}`)
			const before = await entry.inputValue()
			await entry.focus()
			await page.keyboard.insertText('Inserted')
			await expect(entry).toHaveValue(before)
			const cancelled = await entry.evaluate(el => ['paste', 'drop', 'beforeinput'].map(type => !el.dispatchEvent(new Event(type, { bubbles: true, cancelable: true }))))
			expect(cancelled).toEqual([true, true, true])
			await entry.evaluate(el => {
				el.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
				;(el as HTMLInputElement).value = 'Late composition'
				el.dispatchEvent(new InputEvent('input', { bubbles: true, data: 'Late composition', isComposing: true }))
				el.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true }))
			})
			await expect(entry).toHaveValue(before)
		}
		await expect(page.getByTestId('text')).toHaveText('Initial')
		await expect(page.getByTestId('selected')).toHaveText('a')
	})
}

test('disabled transitions preserve outside focus and owned popup inherits context', async ({ page }) => {
	const select = page.locator('#select-entry')
	await select.click()
	await page.getByRole('button', { name: 'Change bindings' }).click()
	await expect(page.getByRole('listbox').locator('xpath=ancestor::*[@dir][1]')).toHaveAttribute('dir', 'rtl')
	await page.getByRole('button', { name: 'Outside', exact: true }).focus()
	await page.getByRole('button', { name: 'Toggle disabled' }).click()
	await expect(page.getByRole('button', { name: 'Outside', exact: true })).toBeFocused()
})

test('live hint slots fall back to props and remove absent descriptions', async ({ page }) => {
	await page.getByRole('button', { name: 'Toggle hint slot' }).click()
	await expect(page.locator('#external')).toHaveAccessibleDescription('Caller description Fallback hint')
	await expect(page.locator('#select-entry')).toHaveAttribute('aria-describedby', 'extra')
	await page.getByRole('button', { name: 'Toggle hint slot' }).click()
	await expect(page.locator('#external')).toHaveAccessibleDescription('Caller description Input guidance')
	await expect(page.locator('#select-entry')).toHaveAccessibleDescription('Caller description Select guidance')
})

test('disabled input blocks implicit Enter without a caller key modifier', async ({ page }) => {
	const entry = page.getByRole('textbox', { name: 'Disabled required' })
	await entry.focus()
	await entry.press('Enter')
	await expect(page.getByTestId('submits')).toHaveText('0')
})

test('source API consumer mounts string, numeric and object values, slots and public refs', async ({ page, pageLog }) => {
	await page.goto('/field-api-cases')
	await expect(page.getByRole('textbox', { name: 'Text', exact: true })).toHaveValue('Text')
	await expect(page.getByRole('spinbutton', { name: 'Number', exact: true })).toHaveValue('42')
	await expect(page.getByRole('combobox', { name: 'Object', exact: true })).toHaveValue('Object')
	await expect(page.getByRole('combobox', { name: 'Numeric', exact: true })).toHaveValue('One')
	await expect(page.getByRole('combobox', { name: 'String', exact: true })).toHaveValue('one')
	await page.getByRole('button', { name: 'Focus', exact: true }).click()
	await expect(page.getByRole('combobox', { name: 'Object', exact: true })).toBeFocused()
	await expect(page.getByRole('combobox', { name: 'Object', exact: true })).toHaveAttribute('aria-expanded', 'false')
	expect(pageLog.vueWarnings).toEqual([])
})

test('open select keeps unique IDs and accessible option state', async ({ page }) => {
	await page.locator('#select-entry').click()
	await expect(page.locator('.bunt-tooltip')).toHaveCount(0)
	const ids = await page.locator('[id]').evaluateAll(elements => elements.map(element => element.id))
	expect(new Set(ids).size).toBe(ids.length)
	await expect(page.getByRole('option', { name: 'Alpha' })).toHaveAttribute('aria-selected', 'true')
	await expect((await axeScan(page, 'main')).violations).toEqual([])
	await page.getByRole('button', { name: 'Change name', exact: true }).click()
	await expect(page.getByRole('listbox')).toHaveAccessibleName('Caller name')
	await page.locator('#select-entry').fill('Missing')
	await expect((await axeScan(page, 'main')).violations).toEqual([])
})
